### ISSUE TITLE
Naming of directories with illegal characters

### ISSUE THREAD

**Issue by rudolphpienaar** [FNNDSC/chrisreloaded#108]
# Naming of directories with illegal characters

## Overview

In preparation for sucking all the DICOM metadata into a database, I iterated over the whole /neuro/users/chris/data tree with a shell command using 'xargs'. This crashed on many directories which in fact had an apostrophe character in their dirname, like

COR_Siemen's_data

instead of 

COR_Siemens_data

## Solution

The dicom unpacker that writes to the filesystem needs to catch this character. Also noticed that some directories have an ";".

So right now, we need to filter out ; and ' in protocol names that become dirnames.

**Comment by NicolasRannou** [comment]
Yes, the ' character was an old bug that was already fixed, but the directory you tried to parse was probably created before the bug was fixed.

I added more special characters (including ;) to the list of characters to be replaced by _, before creating the dirnames and populating the database.

Closed by:
https://github.com/FNNDSC/chrisreloaded/commit/b100df3359e3b1b1be795a1db411c4241b41ca9c
